apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
spec:
  type: ClusterIP
  selector:
    app: nodejs-api-selector
  ports:
    - port: 80
      targetPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
  selector:
    app: "nodejs-api-selector"
